server {
    listen 80;

    access_log off;
    error_log /dev/null crit;

    location / {
        proxy_pass http://frontend:4200;
    }

    location /api {
        proxy_pass http://backend:8080;
    }
}